/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MoneyLoveRouteImport } from './routes/money-love'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as IndexRouteImport } from './routes/index'

const MoneyLoveRoute = MoneyLoveRouteImport.update({
  id: '/money-love',
  path: '/money-love',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merch': typeof MerchRoute
  '/money-love': typeof MoneyLoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merch': typeof MerchRoute
  '/money-love': typeof MoneyLoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merch': typeof MerchRoute
  '/money-love': typeof MoneyLoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/merch' | '/money-love'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merch' | '/money-love'
  id: '__root__' | '/' | '/merch' | '/money-love'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchRoute: typeof MerchRoute
  MoneyLoveRoute: typeof MoneyLoveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/money-love': {
      id: '/money-love'
      path: '/money-love'
      fullPath: '/money-love'
      preLoaderRoute: typeof MoneyLoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchRoute: MerchRoute,
  MoneyLoveRoute: MoneyLoveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
