/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMoneyLoveRouteImport } from './routes/app/money-love'
import { Route as AppMerchRouteImport } from './routes/app/merch'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMoneyLoveRoute = AppMoneyLoveRouteImport.update({
  id: '/money-love',
  path: '/money-love',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMerchRoute = AppMerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/merch': typeof AppMerchRoute
  '/app/money-love': typeof AppMoneyLoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/merch': typeof AppMerchRoute
  '/app/money-love': typeof AppMoneyLoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/merch': typeof AppMerchRoute
  '/app/money-love': typeof AppMoneyLoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/merch' | '/app/money-love'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/merch' | '/app/money-love'
  id: '__root__' | '/' | '/app' | '/app/merch' | '/app/money-love'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/money-love': {
      id: '/app/money-love'
      path: '/money-love'
      fullPath: '/app/money-love'
      preLoaderRoute: typeof AppMoneyLoveRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/merch': {
      id: '/app/merch'
      path: '/merch'
      fullPath: '/app/merch'
      preLoaderRoute: typeof AppMerchRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppMerchRoute: typeof AppMerchRoute
  AppMoneyLoveRoute: typeof AppMoneyLoveRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppMerchRoute: AppMerchRoute,
  AppMoneyLoveRoute: AppMoneyLoveRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
